import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);

        double sumChild = 0; // sum of all the children for the compute the average 

		int twoChild = 0; 
		int threeChild = 0; 
		int fourorMore = 0; 
		

		for (int i = 1; i < T; i++) {

			int countChild = 0;
			//define the first child and add for the count
			int num1 =  generator.nextInt(2) + 1; // number between (1,2)
			int num2 =  generator.nextInt(2) + 1;
		    countChild = 2; 

			while ( num1 == num2 ) { 
				num2 = generator.nextInt(2) + 1; 
				countChild = countChild + 1;

				if (num1 != num2) {
					break; 
				} 
			}


			if ( countChild == 2 ) {
				twoChild++; 
			} else if ( countChild == 3 ) {
				threeChild++; 
			} else if ( countChild >=4 ) {
				fourorMore++; 
			}
			

			sumChild += countChild; 
		}
		



        

		double average =  sumChild /  T; 
		System.out.println("Average:" + " " + ( average ) + " " + "children to get at least one of each gender." );
		System.out.println( "Number of families with 2 children:" + " " + twoChild); 
		System.out.println( "Number of families with 3 children:" + " " + threeChild);
		System.out.println( "Number of families with 4 children:" + " " + fourorMore);    

		if ( twoChild > threeChild && twoChild > fourorMore) {
			System.out.println("The most common number of children is 2.");
		} else if (threeChild > fourorMore && threeChild > twoChild) {
			System.out.println("The most common number of children is 3.");
		} else if (fourorMore > threeChild && fourorMore > twoChild) {
			System.out.println("The most common number of children is 4.");
		}
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
